export const cookieData = [
  {
    domain: ".google.com",
    expirationDate: 1749146896.934591,
    hostOnly: false,
    httpOnly: false,
    name: "SEARCH_SAMESITE",
    path: "/",
    sameSite: "strict",
    secure: false,
    session: false,
    storeId: "0",
    value: "CgQI4JwB",
  },
  {
    domain: ".google.com",
    expirationDate: 1749147007.579068,
    hostOnly: false,
    httpOnly: true,
    name: "AEC",
    path: "/",
    sameSite: "lax",
    secure: true,
    session: false,
    storeId: "0",
    value: "AZ6Zc-UjtdXeNFFI-UB7Pbb6_OfGPdaj0THP_mK7AECBqMlI-V3CEpBq_A",
  },
  {
    domain: ".google.com",
    expirationDate: 1767154119.341826,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-1PSIDTS",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "sidts-CjAB7wV3sT8QZk0iFTdsQMVVGZV1nSJrW2V6o7-FumJ4F_95cSE8KvEzKMqVYo0W6_AQAA",
  },
  {
    domain: ".google.com",
    expirationDate: 1767154119.342182,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-3PSIDTS",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "sidts-CjAB7wV3sT8QZk0iFTdsQMVVGZV1nSJrW2V6o7-FumJ4F_95cSE8KvEzKMqVYo0W6_AQAA",
  },
  {
    domain: ".google.com",
    expirationDate: 1770178457.505095,
    hostOnly: false,
    httpOnly: false,
    name: "SID",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value:
      "g.a000rwg2W-afXCkXOxqMOlFl1dlA7cZbXSiGtOgnJZSd7l18j_IzaF6Ohu4JhS_neGJNN7_qwAACgYKAf4SARISFQHGX2MiHKgY302KIH9j19qAWGcu7RoVAUF8yKpnwXXuDESBKUnC1qBUdkil0076",
  },
  {
    domain: ".google.com",
    expirationDate: 1770178457.505269,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-1PSID",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "g.a000rwg2W-afXCkXOxqMOlFl1dlA7cZbXSiGtOgnJZSd7l18j_Izh_bWFNI1twPLNxO9uz15BwACgYKAfkSARISFQHGX2Mi6F2Ps0TTKWbdTR5Xvr7vKRoVAUF8yKrApQp-5_Zpk5FDMvXBy4MI0076",
  },
  {
    domain: ".google.com",
    expirationDate: 1770178457.505432,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-3PSID",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "g.a000rwg2W-afXCkXOxqMOlFl1dlA7cZbXSiGtOgnJZSd7l18j_IztOzUo1jW_JGzuIxwBNmREQACgYKAYUSARISFQHGX2MiGBr55pKxcJoatd34TJhQsRoVAUF8yKpZbl-kC9JGV9JJ7KXLEzYn0076",
  },
  {
    domain: ".google.com",
    expirationDate: 1770178457.506011,
    hostOnly: false,
    httpOnly: true,
    name: "HSID",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "AQRFPeHvlpf5ba6M3",
  },
  {
    domain: ".google.com",
    expirationDate: 1770178457.506158,
    hostOnly: false,
    httpOnly: true,
    name: "SSID",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: false,
    storeId: "0",
    value: "AtHhp0o3ScvCszk_h",
  },
  {
    domain: ".google.com",
    expirationDate: 1770178457.506298,
    hostOnly: false,
    httpOnly: false,
    name: "APISID",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "uWUYvYzBPnrNKmdR/ANGXK4XhthJKebm3P",
  },
  {
    domain: ".google.com",
    expirationDate: 1770178457.506448,
    hostOnly: false,
    httpOnly: false,
    name: "SAPISID",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: false,
    storeId: "0",
    value: "4winPvdukQ-xxFYP/APFJhJ8sIqhTEem5n",
  },
  {
    domain: ".google.com",
    expirationDate: 1770178457.506814,
    hostOnly: false,
    httpOnly: false,
    name: "__Secure-1PAPISID",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: false,
    storeId: "0",
    value: "4winPvdukQ-xxFYP/APFJhJ8sIqhTEem5n",
  },
  {
    domain: ".google.com",
    expirationDate: 1770178457.507201,
    hostOnly: false,
    httpOnly: false,
    name: "__Secure-3PAPISID",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value: "4winPvdukQ-xxFYP/APFJhJ8sIqhTEem5n",
  },
  {
    domain: ".google.com",
    expirationDate: 1751429318.381857,
    hostOnly: false,
    httpOnly: true,
    name: "NID",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "520=V15w5WSCvKDFBVsRH7nZU_krY-LWe3Fla9huSdlUA2vkwmf3hyVLNjmeMWmUJjZEIDwg-SqtiOpJmAPPbu8kPRMgD2yxxFxsohba6Cat-nRcYlMdbmwKSKwNNHpUaAx1LQZ_YPxtQbUwJICZdqzyHmsB-yC-73ilqF3uVaaa7pmfhI58DKBjNsDp7uxnU5Lnf7lAGcsBxj0njnv5plfYA-spSuFEKgGzoRTxgD66Klk3pvV_vJOIFXVxOfDMxj3zvbsXSk6psFGH7nG-vQjy0PiSpSetZ0fnLwsp_VEp24yGU3VuaQrPmjB_m53pAGjZRQyWFg9ZdMSjEZb27b5IpbKUftejooHh9wyW9wAu3A0nWgEr811T96rvLYwS4da74lCuywmKbOrAcb8tehMgtZh9hYISgSFBcpneYI_UdBUoXIrcgLEc2HH8R-QZsfqBMtBfnPGNHsHuowuOJKRqD36lSICeF9KcJuo_bvCPGnDRpaLJ5K-RIOwYstpz0wHjFywMEkj0GTX-XNYbpjuUCwsD3bvXoD00gQEprRfBUIBnbnBm9z0joqGvwGOjYFBKlF0-vSPJAoFDTviIxaCtR2AYrK_78v5MIsfV0oYvEuZpB_u6k72ZlYNb5lpYoWLuQEkUIJuWg9J2JoQGJ5P61xA5OCuYU2nU2tN-brdll2tAEdRHbu1UQSLY-Vg8XDa_k2CetNw2Nuvkuv0yRhApwg28hHm0fG6kxt3wAiUu",
  },
  {
    domain: "www.google.com",
    expirationDate: 1735619068,
    hostOnly: true,
    httpOnly: false,
    name: "DV",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value:
      "g9ZAMe7L8W5U8JiFc16AWAbelcGuQVmXimc7DQWIRQAAAEBL1W1MikEpNgAAAOBRX6N8aZALLQAAALwkxYOqKaGkEAAAAA",
  },
  {
    domain: ".google.com",
    expirationDate: 1767154540.689252,
    hostOnly: false,
    httpOnly: false,
    name: "SIDCC",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value:
      "AKEyXzUNXhoYjeICU5ppCadeAWtkuXv6JkzSdMaHcWYJukwOyivGjIJ4rNtmcB3wwM_Ob9fRnP4",
  },
  {
    domain: ".google.com",
    expirationDate: 1767154540.689437,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-1PSIDCC",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "AKEyXzXeDI8aD_kkARdFpeZ30SaWTq5CZGNn7y1pCS4AbocRpOEbkGkAL5IReWs2bdhCxokrJlU",
  },
  {
    domain: ".google.com",
    expirationDate: 1767154540.689515,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-3PSIDCC",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "AKEyXzWRe7YXor8SJj9fHnrrUgjdyDEVuXeBc9Z-pw31TwA8itrYqkyXyEseyVe-ShpfyFsGUA",
  },
];
